### ISSUE TITLE
Starting up with the tutorial

### ISSUE THREAD

**Issue by digilevi2006** [beeware/briefcase#494]
Hi everyone and the devs,

Sorry if this might have been answered already but I searched all issues and I didn't find the answer.

I am on this step `https://docs.beeware.org/en/latest/tutorial/tutorial-3.html`
and when I run the app it says `Unable to start app helloworld.`

If it's in Dev mode, it's working perfectly. 
The app is not entirely only from the tutorial, I added `multilineTextInput` that outputs the `response.text` of a `requests.get `
 I also added a Label that has the welcome text and changes with the `('Fetching ' +url)`  when you click the button and
 with `yield 3` to just wait for that Fetching notification before pasting the `r.text` to the multilinetextinput.value .

When I run the app on Dev mode, I get this:

>  `[Winforms] Not implemented: MultilineTextInput.set_placeholder()`

So, I tried to create, build and run but I get this:

> `Unable to start app helloworld.`

I tried these solutions:
1. delete windows folder then recreate
2. overwrite the folder.
3. dev mode with -d switch and re create folder.
4. package the app into msi but nothing happens when I open the app
5. I even opened microsoft store which I thought might be blocking the running 

But no luck.
Not sure what's happening but appreciate any help for a starter like me.

Thanks.

**Comment by freakboy3742** [comment]
Thanks for the report - and sorry to hear you're having difficulties. Unfortunately, debugging runtime failures on Windows can a little annoying. 

The good news is that the warning about `set_placeholder()` isn't anything to worry about. It's letting you know the code (explicitly or implicitly) is using a feature that isn't available on Winforms. However, the app will continue to run - it just won't have a placeholder text.

You've mentioned that you've made a few extra changes to the app; I want to confirm that you haven't added an external library or some dependency other than Toga. If you have, *that* would definitely explain the behavior you're seeing. Any dependencies for your app must be listed in `pyproject.toml`.

Assuming that's not the problem; the next thing to try is to manually start the app from the command line. Open a clean terminal (and *don't* activate the virtual environment), and run:

    "windows\Hello World\src\python\python.exe" -m hello_world

(You may need to alter the path and final module name to match the formal and app name that you chose when you ran the Briefcase wizard to start your project). 

This should reproduce what happens when you run your app with `briefcase run`, but the console output (and the cause of any crashes) will be visible. What error (if any) do you see?

**Comment by digilevi2006** [comment]
Hi Russell@freakboy3742 ,

Thank you for your reply.

I've definitely added some modules, the requests, time with sleep. So, I tried to comment those, recreated, built, and now it's working on "run". Thank you for showing the way.

Now, I've inspected the toml, I'm not sure where to put the modules as I see different "require" which I assume to put the modules. But if it will be explained in the tutorial, it's okay I'll just continue with it.


just a side question, is it possible to bundle so files to android or arm to ios? I tried with kivy but no success.

Thanks again Russell.

**Comment by freakboy3742** [comment]
You've identified the right place for dependencies; the `requires` list is the list of dependencies, specified as pip requirements (e.g., `mypackage>=1.2.3`). There's a `requires` list at the top level of the project; that list can be appended to on a per-platform basis by adding a `requires` list in the platform sections for your app.

As for adding .so files - See #471 for the discussion about dependencies with binary components. In short - it's *possible*, but not something that is as simple as "pip install" at present. If you mean completely standalone .so files - yes, that's possible; however, you'll need to manage the inclusion yourself. Unfortunately, I can't point you at documentation for either case.

Closing this ticket as the original question appears to have been resolved; if you have follow up questions, feel free to ask here or on a new ticket.

**Comment by digilevi2006** [comment]
@freakboy3742 ,
Hi Russell,

I just want to make sure I did the correct layout of the ".toml"

```
[tool.briefcase.app.helloworld.windows]
requires = [
    'toga-winforms>=0.3.0.dev20', 'requests' , 'time', 'threading'
]
```

when I did this, the app hangs when it gets to the requests code. I tried doing it on a threading but there is no response on the button click.(or maybe my code is also wrong). If the solution is the threading, it's fine, you don't have to answer here. I'll just search around.

> By the way, can I have one requires statement for all of the build? or should I need to indicate requires to each platform?

> Last thing is about this page:
        [https://toga.readthedocs.io/en/v0.2.15/reference/supported_widgets.html](url)
 is it updated?
If so, then the multilineTextInput is not supported in android, right? I also went ahead and tried to find documentation about having to build(or convert?) the code into "cocoa" so that I can have all the widgets supported?


This is the code I got so far, if you have time... 👍 



```
import toga ,requests,time, threading
from toga.style import Pack
from toga.style.pack import COLUMN, ROW
from time import sleep

class HelloWorld(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        name_label = toga.Label(
            'Your name: ',
            style=Pack(padding=(0, 5))
        )
        self.name_input = toga.TextInput(style=Pack(flex=1))
        # self.name_input.focus =True
        self.lbl_notif = toga.Label('Welcome to viewYout')
        self.content = toga.MultilineTextInput(style=Pack(flex=1))

        
        name_box = toga.Box(style=Pack(direction=ROW, padding=5))
        name_box.add(name_label)
        name_box.add(self.name_input)
        
        notif_box = toga.Box(style=Pack(direction=COLUMN, padding=5))
        notif_box.add(self.lbl_notif)
        
        content_box = toga.Box(style=Pack(direction=COLUMN, padding=5))
        content_box.add(self.content)
        
        button = toga.Button(
            'Say Hello!',
            on_press=self.startSay,
            style=Pack(padding=5)
        )

        main_box.add(name_box)
        main_box.add(button)
        main_box.add(notif_box)
        main_box.add(content_box)
        

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()
    
    def say_hello(self, widget):
        # print("Hello", self.name_input.value)
        self.main_window.info_dialog(
            'Hi there!',
            "Hello, {}".format(self.name_input.value)
        )

        url ='https://google.com'
        r = requests.get(url)
        self.lbl_notif.text = ('Fetching '+url)
        # print(r.text)
        # sleep(5)
        yield 3  #same as sleep
        self.content.value = r.text
        self.lbl_notif.text = ('Done!')
       
    def startSay(self, widget):
        hello = threading.Thread(target=self.say_hello, args=(widget,))
        hello.start() 
        hello.join()
        
def main():
    return HelloWorld()
```

**Comment by freakboy3742** [comment]
As described in the [docs](https://briefcase.readthedocs.io/en/latest/reference/configuration.html#requires), `requires` is a cumulative setting, so you can put *common* requirements at the application level (under `[tool.briefcase.app.myapp]`), and platform specific requirements at the platform level (`[tool.briefcase.app.myapp.winforms]`), and the two lists will be concatenated.

I'm somewhat confused though - you've been talking about running an Android app, but the pyproject.toml section you've provided is for winforms. Which platform are you running on? On what platforms are you seeing crashes? Which platforms are giving lockups?

The docs page you've referenced is for an out of date version (on the v0.2 branch); the current docs are [here]) https://toga.readthedocs.io/en/latest/reference/widgets_by_platform.html). However, as I said, that table is out of date. MultilineTextInput *does* exist on Android.

Lastly, there is no "conversion" guide for macOS - because the same code should run on all platforms (with the proviso that the Toga widgets you're using actually need to exist on the platforms you're targeting). If you `pip install --pre toga`, it will install the appropriate Toga backend for your current platform; similarly, if you're using briefcase to package your app, `briefcase create` will build for the current platform.

**Comment by digilevi2006** [comment]
Hi Russell @freakboy3742 ,

I am targeting all platform and with ease and smooth transition. 

I've removed the threading part and now it doesn't hang. I'm not sure what happened. But just to make sure, can briefcase handle requests and sleep without threading? Or it should hang as normal outcome...

Also, I tried the same code in android, it hangs. I tried with the thread, still hangs. Can android handle requests? I am also thinking of adding selenium in the scene, but I'm skeptic now that it freezes on requests. 

And I've read the discussion you mentioned above that executables(i.e. geckodriver) are not possible to include in the build.

So, maybe I just need to stop targeting python GUI and mobile versions of my app for now as I believe, not possible at the moment. 

But thank you for your help.

**Comment by freakboy3742** [comment]
Yes, Android should be able to handle requests.

Threading *should* also work; however, threading *can* have some interesting interactions with the operation of GUI loops, so it's generally advisable to avoid threading for anything that is going to interact with the GUI. This will be especially true on Windows, which has it's own parallel threading tooling built into Winforms.

If you're looking to do work in the background, Toga has full support for asyncio built in. Any event handler can be an awaitable co-routine, which enables you to invoke things like network requests without locking up your GUI thread.

As for `pip install --pre toga` - I'm not exactly sure what you're asking. `pip install` will install for your *current* platform - the platform where you're running the invocation of `pip`. You don't *ever* need to install more than one version of Toga - you need the one for the platform where you're currently running. 

Installing the right tools for "all" platforms is what Briefcase is for - you define the requirements for each platform, and then package the app *for that platform*. The output of Briefcase isn't a "universal" application - it's a separate installer/binary for each platform you target.

**Comment by digilevi2006** [comment]
Hi Russell,

Thanks again for your reply.

I didn’t do the “pip install —pre toga” because it was not in the steps of the tutorial. 😅
Should I do it? I’m just doing all the pip inside my virtualenv and for all the platform(windows android,etc)

So, why does it hang when i run the same code in android? I tried with or without the thread? Could it be my installation? Should i start over?

Thanks again

**Comment by freakboy3742** [comment]
Ok - I'm getting thoroughly confused. Let's step back.

Have you successfully run the *entire* briefcase tutorial, *without* modifications? A lot of the questions you are asking seem to stem from misunderstandings about what Briefcase is doing, and how it does it. If you haven't - can I please suggest that you run the tutorial *as written*, once, all the way through.

After that - can I suggest that you change *one thing at a time*, on a *single* platform, rather than trying to change mutiple things, on multiple platforms. It's a lot easier to answer a specific question about a specific *single* error, on a *single* platform, rather than trying to work out which different platform is causing problems in each sentence of a question.

**Comment by digilevi2006** [comment]
You’re correct. I need to do the tutorial first as is, without any modifications. I will start from beginning.  I was just excited that the requests finally worked in windows and i tried it in android. But i will try first without any modifications.

Thanks Russell. 😊

**Comment by digilevi2006** [comment]
Hi Russell, @freakboy3742 

I have restarted the tutorial and went through building and running it for android. It was perfect and working as expected.

So I went forward and added the multilineTextInput and inserting the name value to the value of the textinput and still was working both windows and android

Now, I went forward to try out the requests and this is where I am now as it hangs when getting it. It actually does its job though and paste the` response.text` to the multiLineTextInput

I tried adding a thread like so:

   ```
 def startSay(self):
        hello = threading.Thread(target=self.say_hello)
        hello.start()
        hello.join()
```

but error says `startSay() takes 1 positional argument but 2 were given`

also tried this:

  ```
 def startSay(self):
        hello = threading.Thread(target=self.say_hello, args=(widget, ))
        hello.start()
        hello.join()
```

but same error.

By the way, this is the say_hello:
```

    def say_hello(self,widget):
        # if self.name_input.value:
        #     name = self.name_input.value
        # else:
        #     name = 'stranger'
        # self.content.value = self.content.value + name + '\n'
        response = requests.get('https://pastebin.com/raw/0BbQgabr')
        self.lbl_notif.text = ('Fetching... ')
        self.content.value = response.text  #insert text into multiLineTextInput
        self.lbl_notif.text = ('Done!')
```

Any suggestions?
Thanks
